--- # Install Raspberry Pi specific tweaks
- hosts: rpis 
  become: true

  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Check if swap enabled
    shell: swapon --show | wc -l
    register: swap_enabled

  - name: Disable swap
    shell: "{{ item }}"
    with_items: 
      - dphys-swapfile swapoff
      - dphys-swapfile uninstall
      - update-rc.d dphys-swapfile disable
    when: swap_enabled.stdout != "0"

  - name: Uninstall swap
    apt: name=dphys-swapfile state=absent purge=yes autoremove=yes

  - name: Clone Log2RAM repo
    git: repo=https://github.com/azlux/log2ram.git clone=yes dest=/home/ansible/log2ram

  - name: Check if Log2RAM enabled
    shell: df -h | grep log2ram | wc -l
    register: log2ram_enabled

  - name: Set Log2RAM Install Script to Executable
    file: path=/home/ansible/log2ram/install.sh mode=0755
    when: log2ram_enabled.stdout == "0"

  - name: Execute Log2RAM Install Script
    command: sh /home/ansible/log2ram/install.sh
    when: log2ram_enabled.stdout == "0"

  - name: Reboot to enable changes
    reboot: 
    when: log2ram_enabled.stdout == "0"
